// <auto-generated />
using System;
using CinemApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CinemApi.Migrations
{
    [DbContext(typeof(FilmDbContext))]
    partial class FilmDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.7");

            modelBuilder.Entity("CinemApi.Models.Film", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cim")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Ev")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Mufaj")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RendezoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RendezoId");

                    b.ToTable("Films");
                });

            modelBuilder.Entity("CinemApi.Models.Rendezo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nemzetiseg")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nev")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Rendezos");
                });

            modelBuilder.Entity("CinemApi.Models.Vetites", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("FilmId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Idopont")
                        .HasColumnType("TEXT");

                    b.Property<int>("JegyAr")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Terem")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FilmId");

                    b.ToTable("Vetitesek");
                });

            modelBuilder.Entity("CinemApi.Models.Film", b =>
                {
                    b.HasOne("CinemApi.Models.Rendezo", "Rendezo")
                        .WithMany("Films")
                        .HasForeignKey("RendezoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rendezo");
                });

            modelBuilder.Entity("CinemApi.Models.Vetites", b =>
                {
                    b.HasOne("CinemApi.Models.Film", "Film")
                        .WithMany("Vetitess")
                        .HasForeignKey("FilmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Film");
                });

            modelBuilder.Entity("CinemApi.Models.Film", b =>
                {
                    b.Navigation("Vetitess");
                });

            modelBuilder.Entity("CinemApi.Models.Rendezo", b =>
                {
                    b.Navigation("Films");
                });
#pragma warning restore 612, 618
        }
    }
}
